//go:build !lib

// Source mode: compile C sources directly with CGO.
// Usage: go build (default)
// Requires: CGO_CFLAGS_ALLOW="-mavx.*|-msse.*|-mfma|-mavx512.*"
// Generated by CMake - DO NOT EDIT MANUALLY
package optim

/*
#cgo CFLAGS: -I${SRCDIR}/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/include
#cgo CFLAGS: -I${SRCDIR}/modules/platform/third_party/gmp
#cgo CFLAGS: -I${SRCDIR}/modules/platform/third_party/mpfr/src
#cgo CFLAGS: -I${SRCDIR}/modules/math/include
#cgo CFLAGS: -I${SRCDIR}/modules/ds/include
#cgo CFLAGS: -I${SRCDIR}/optim-c
#cgo CFLAGS: -I${SRCDIR}/modules/platform/src -O2 -Wall -std=c11 -mavx2 -mfma
#cgo linux CFLAGS: -D_POSIX_C_SOURCE=200112L
#cgo linux LDFLAGS: ${SRCDIR}/modules/math/build/linux_amd64/libfinkit_math_static.a ${SRCDIR}/modules/ds/build/linux_amd64/libfinkit_ds_static.a ${SRCDIR}/modules/platform/build/linux_amd64/libfinkit_platform_static.a -lm -lgcov
#cgo darwin,arm64 LDFLAGS: ${SRCDIR}/modules/math/build/darwin_arm64/libfinkit_math_static.a ${SRCDIR}/modules/ds/build/darwin_arm64/libfinkit_ds_static.a ${SRCDIR}/modules/platform/build/darwin_arm64/libfinkit_platform_static.a -lm
#cgo darwin,amd64 LDFLAGS: ${SRCDIR}/modules/math/build/darwin_x86_64/libfinkit_math_static.a ${SRCDIR}/modules/ds/build/darwin_x86_64/libfinkit_ds_static.a ${SRCDIR}/modules/platform/build/darwin_x86_64/libfinkit_platform_static.a -lm
#cgo windows LDFLAGS: ${SRCDIR}/modules/math/build/windows_amd64/libfinkit_math_static.a ${SRCDIR}/modules/ds/build/windows_amd64/libfinkit_ds_static.a ${SRCDIR}/modules/platform/build/windows_amd64/libfinkit_platform_static.a -lm


#include "least_squares.h"
#include "greeks.h"
#include "var_parametric.h"
#include "var_historical.h"
#include "var_monte_carlo.h"

// Platform sources (dependency)
#include "simd_detect.c"
#include "fc_bignum_init.c"
#include "fc_bigint.c"
#include "fc_bigfloat.c"
#include "fc_precision.c"
#include "mem_aligned.c"
#include "error.c"
#include "fc_init.c"

// Platform-specific sources
#if defined(__linux__)
  #include "modules/platform/src/platform_linux.c"
#elif defined(__APPLE__)
  #include "modules/platform/src/platform_macos.c"
#elif defined(_WIN32)
  #include "modules/platform/src/platform_win.c"
#endif

// optim sources
#include "optim-c/least_squares.c"
#include "optim-c/greeks.c"
#include "optim-c/var_parametric.c"
#include "optim-c/var_historical.c"
#include "optim-c/var_monte_carlo.c"
*/
import "C"

func init() {
	C.fc_init()
}
